export const TEST_IDS = {
  APP: "APP",
  ALERT: "ALERT",
  BUTTON: "BUTTON",
  DELETE_BUTTON: "DELETE_BUTTON",
  INPUT: "INPUT",
  ISIN_FORM: "ISIN_FORM",
  OVERLAY: "OVERLAY",
  TABLE_ROW: "TABLE_ROW",
};
